version: "3.7"
services:
  postgres:
    environment:
      POSTGRES_DB: scola
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/lib:/docker-entrypoint-initdb.d/00_lib
      - ./postgres/docker-entrypoint-initdb.d/load.sh:/docker-entrypoint-initdb.d/load.sh
      - $PWD/.docker/postgres/docker-entrypoint-initdb.d/app:/docker-entrypoint-initdb.d/01_app
