version: "3"
services:
  postgres:
    environment:
      POSTGRES_DB: scola
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: "postgres:13-alpine"
    networks:
      - scola
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./postgres/initdb.d/lib:/docker-entrypoint-initdb.d/lib
      - ./postgres/initdb.d/load.sh:/docker-entrypoint-initdb.d/load.sh
      - $PWD/.docker/postgres/initdb.d/app:/docker-entrypoint-initdb.d/app
