version: "3.7"
services:
  node:
    command: >
      sh -c "
        npm ci &&
        npm run node --trace-warnings
      "
    env_file: $PWD/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "node:14"
    ports:
      - "9229:9229"
    volumes:
      - $PWD/dist:/usr/src/app/dist
      - $PWD/package.json:/usr/src/app/package.json
      - $PWD/package-lock.json:/usr/src/app/package-lock.json
    working_dir: /usr/src/app
