version: "3.7"
services:
  node:
    command: >
      sh -c "
        yarn install --frozen-lockfile --ignore-optional --production &&
        yarn run exec
      "
    env_file: $PWD/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "node:14"
    ports:
      - "9229:9229"
    volumes:
      - $PWD/dist:/usr/src/app/dist
      - $PWD/package.json:/usr/src/app/package.json
      - $PWD/yarn.lock:/usr/src/app/yarn.lock
    working_dir: /usr/src/app
