version: "3"
services:
  node:
    command: >
      sh -c "
        yarn install --frozen-lockfile --production &&
        yarn run exec
      "
    depends_on:
      - redis
    env_file: $PWD/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "node:14"
    networks:
      - scola
    ports:
      - "9229:9229"
    volumes:
      - $PWD/dist/server:/usr/src/app/dist/server
      - $PWD/package.json:/usr/src/app/package.json
      - $PWD/yarn.lock:/usr/src/app/yarn.lock
    working_dir: /usr/src/app
