version: "3"
services:
  mysql:
    image: "mysql:8.0.18"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: scola
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "0.0.0.0:3306:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - $PWD/.deploy/mysql/initdb.d:/docker-entrypoint-initdb.d
