version: "3"
services:
  redis:
    command: redis-server /etc/redis/conf.d/redis.conf
    image: "redis:6-alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf.d:/etc/redis/conf.d
