version: "3"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: scola
      MYSQL_ROOT_PASSWORD: root
    image: "mysql:8.0.18"
    ports:
      - "0.0.0.0:3306:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./mysql/initdb.d/lib:/docker-entrypoint-initdb.d/lib
      - ./mysql/initdb.d/load.sh:/docker-entrypoint-initdb.d/load.sh
      - $PWD/.docker/mysql/initdb.d/app:/docker-entrypoint-initdb.d/app
