version: "3.7"
services:
  nginx:
    image: "nginx:1-alpine"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - $PWD/node_modules/@scola/lib/.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - $PWD/node_modules/@scola/lib/.docker/nginx/data/index.html:/www/nginx/index.html
      - $PWD/node_modules/@scola/lib/dist/:/www/nginx/scola/
      - $PWD/dist/:/www/nginx/app/