version: "3"
services:
  nginx:
    depends_on:
      - node
    image: "nginx:1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/dist/client:/usr/share/nginx/html
      - ./nginx/docker-entrypoint.d/https.sh:/docker-entrypoint.d/https.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
