version: "3"
services:
  nginx:
    image: "nginx:1-alpine"
    ulimits:
      nofile: 1048576
    volumes:
      - $PWD/dist/client:/usr/share/nginx/html
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
