version: "3"
services:
  nginx:
    depends_on:
      - node
    image: "nginx:1-alpine"
    networks:
      - scola
    ports:
      - "3000:3000"
    volumes:
      - $PWD/dist/client:/usr/share/nginx/html/dist/client
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html/index.html:/usr/share/nginx/html/index.html
      - ./nginx/snippets:/etc/nginx/snippets
