version: "3.7"
services:
  nginx:
    image: "nginx:1-alpine"
    volumes:
      - $PWD/dist/client:/usr/share/nginx/html
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/main-dev.conf:/etc/nginx/conf.d/main.conf
