export default {
  action_cancel: 'Annuleren',
  action_login: 'Inloggen',
  action_ok: 'OK',
  action_register: 'Registeren',
  action_reset_confirm: 'Wijzigen',
  action_reset_request: 'Versturen',
  action_save: 'Opslaan',
  email_subject_login: 'U bent ingelogd',
  email_subject_login_hotp: 'Inloggen',
  email_subject_register: 'Uw account is geregistreerd',
  email_subject_register_hotp: 'E-mailadres registeren',
  email_subject_register_identity: 'Account registeren',
  email_subject_reset_request: 'Wachtwoord wijzigen',
  email_subject_unregister_hotp: 'E-mailadres verwijderen',
  email_subject_unregister_identity: 'Uw account is gewijzigd',
  email_subject_update_user: 'Account gewijzigd',
  email_text_login: 'Uw account is gebruikt om in te loggen op een nieuw apparaat op $(date?dateStyle=full&timeStyle=short)d.\n\nAls u dit niet zelf hebt gedaan, verander dan zo snel mogelijk uw wachtwoord via [deze link]($(url)s).',
  email_text_login_hotp: 'Uw eenmalige code is:\n\n**_$(token)s_**',
  email_text_register: 'Er is een account geregisteerd op $(date?dateStyle=full&timeStyle=short)d.\n\nAls u dit niet zelf hebt gedaan, dan kunt u dit ongedaan maken via [deze link]($(url)s).\n(Let op: de link is geldig tot $(token.date_expires?dateStyle=full&timeStyle=short)d.)',
  email_text_register_hotp: 'Uw eenmalige code is:\n\n**_$(token)s_**',
  email_text_register_identity: 'Er is een account geregistreerd op $(date?dateStyle=full&timeStyle=short)d.\n\nU kunt deze registratie bevestigen via [deze link]($(url)s).\n(Let op: de link is geldig tot $(token.date_expires?dateStyle=full&timeStyle=short)d.)',
  email_text_reset_request: 'Er is een link aangevraagd om het wachtwoord van uw account te wijzigen op $(date?dateStyle=full&timeStyle=short)d.\n\nAls u dit niet zelf hebt gedaan, dan kunt u deze e-mail negeren.\n\nU kunt uw wachtwoord wijzigen via [deze link]($(url)s).\n(Let op: de link is geldig tot $(token.date_expires?dateStyle=full&timeStyle=short)d.)',
  email_text_unregister_hotp: 'Uw eenmalige code is:\n\n_$(token)s_',
  email_text_unregister_identity: 'Er is een aanvraag gedaan om uw account te verwijderen op $(date?dateStyle=full&timeStyle=short)d.\n\nAls u dit niet zelf hebt gedaan, dan kunt u deze e-mail negeren.\n\nU kunt uw account verwijderen via [deze link]($(url)s).\n(Let op: de link is geldig tot $(token.date_expires?dateStyle=full&timeStyle=short)d.)',
  email_text_update_user: 'Uw account is gewijzigd op $(date?dateStyle=full&timeStyle=short)d.\n\nAls u dit niet zelf hebt gedaan, verander dan zo snel mogelijk uw wachtwoord via [deze link]($(url)s).',
  err_audio: 'Er is een fout opgetreden in de audio.',
  err_drawer: 'Er is een fout opgetreden in de grafiek.',
  err_idb: 'Er is een fout opgetreden in de database.',
  err_img: 'Er is een fout opgetreden in de afbeelding',
  err_recorder: 'Er is een fout opgetreden in de recorder',
  err_requester: 'Er is een fout opgetreden in de aanvraag.',
  err_requester_400: 'De invoer is ongeldig.',
  err_requester_401: 'U hebt geen toegang tot deze gegevens.',
  err_requester_403: 'U hebt geen toegang tot deze gegevens.',
  err_requester_404: 'De gegevens konden niet worden gevonden.',
  err_requester_405: 'De aanvraag is ongeldig.',
  err_requester_412: 'Er zijn nieuwere gegevens gevonden op de server.',
  err_requester_415: 'De aanvraag is ongeldig.',
  err_requester_500: 'Er is een fout opgetreden op de server.',
  err_requester_502: 'Er is een fout opgetreden op de server.',
  err_validator_bad_input_array: 'Voer een geldige rij in',
  err_validator_bad_input_boolean: 'Voer een geldige waarde in',
  err_validator_bad_input_checkbox: 'Voer een geldige waarde in',
  err_validator_bad_input_color: 'Voer een geldige kleur in',
  err_validator_bad_input_date: 'Voer een geldige datum in',
  err_validator_bad_input_datetimelocal: 'Voer een geldige datum in',
  err_validator_bad_input_email: 'Voer een geldig e-mailadres in',
  err_validator_bad_input_fieldset: 'Voer een geldige waarde in',
  err_validator_bad_input_file: 'Voer een geldig bestand in',
  err_validator_bad_input_number: 'Voer een geldig getal in',
  err_validator_bad_input_operator: 'Voer een geldige operator in',
  err_validator_bad_input_order: 'Voer een geldige richting in',
  err_validator_bad_input_radio: 'Voer een geldige waarde in',
  err_validator_bad_input_range: 'Voer een geldig getal in',
  err_validator_bad_input_select: 'Voer een geldige waarde in',
  err_validator_bad_input_selectmultiple: 'Voer een geldige waarde in',
  err_validator_bad_input_tel: 'Voer een geldig telefoonnummer in',
  err_validator_bad_input_text: 'Voer een geldige tekst in',
  err_validator_bad_input_time: 'Voer een geldige tijd in',
  err_validator_bad_input_url: 'Voer een geldige URL in',
  err_validator_identity: 'Minstens een van de velden e-mail, telefoon of gebruikersnaam is verplicht.',
  err_validator_pattern_mismatch: 'Voer een geldige waarde in',
  err_validator_range_overflow: 'Voer een getal in kleiner dan $(max)n',
  err_validator_range_underflow: 'Voer een getal in groter dan $(min)n',
  err_validator_step_mismatch: 'Voer een getal in als veelvoud van $(step)n',
  err_validator_too_long: 'Voer een tekst in korter dan $(maxLength)n tekens',
  err_validator_too_short: 'Voer een tekst in langer dan $(minLength)n tekens',
  err_validator_type_mismatch_email: 'Voer een geldig e-mailadres in',
  err_validator_type_mismatch_url: 'Voer een geldige URL in',
  err_validator_value_missing: 'Dit veld is verplicht',
  err_video: 'Er is een fout opgetreden in de video.',
  err_worker: 'Er is een fout opgetreden in de worker.',
  hint_reset_request: 'U ontvangt een bericht met een link om uw wachtwoord te wijzigen.',
  hint_user_auth_password: 'Gebruik indien mogelijk een wachtwoordmanager om een wachtwoord aan te maken. Voer 8 of meer tekens in met een mix van letters, nummers en tekens.',
  hint_user_email_auth_login: 'Ontvang een e-mail nadat u bent ingelogd.',
  hint_user_email_auth_update: 'Ontvang een e-mail nadat uw account is gewijzigd.',
  hint_user_identity: 'Minstens een van de velden e-mail, telefoon of gebruikersnaam is verplicht.',
  link_login: 'Inloggen',
  link_register: 'Account registeren',
  link_reset_request: 'Wachtwoord vergeten',
  message_reset_confirm_expired: 'De link is verlopen. U kunt hierboven een nieuwe link aanvragen.',
  ok_login: 'U bent ingelogd.',
  ok_login_code: 'Voer een backup code hieronder in:',
  ok_login_hotp_email: 'Een eenmalige code is verstuurd naar $(email)s. Voer deze code hieronder in:',
  ok_login_hotp_tel: 'Een eenmalige code is verstuurd naar $(tel)s. Voer deze code hieronder in:',
  ok_login_identity: 'Voer hieronder uw wachtwoord in:',
  ok_login_totp: 'Voer hieronder de code van uw authenticator in:',
  ok_logout: 'U bent uitgelogd.',
  ok_register: 'Uw account is geregistreerd. U kunt nu inloggen.',
  ok_register_codes_confirm: 'Uw backup codes zijn geregistreerd.',
  ok_register_codes_request: 'Uw backup codes zijn:',
  ok_register_hotp_email_confirm: 'Uw e-mailadres is geregistreerd.',
  ok_register_hotp_email_request: 'Een eenmalige code is verstuurd naar $(email)s. Voer deze code hieronder in:',
  ok_register_hotp_tel_confirm: 'Uw telefoonnummer is geregistreerd.',
  ok_register_hotp_tel_request: 'Een eenmalige code is verstuurd naar $(tel)s. Voer deze code hieronder in:',
  ok_register_identity_email: 'Een bericht ter bevestiging van uw registratie is verstuurd naar $(email)s. U moet uw registratie bevestigen voordat u kunt inloggen.',
  ok_register_identity_tel: 'Een bericht ter bevestiging van uw registratie is verstuurd naar $(tel)s. U moet uw registratie bevestigen voordat u kunt inloggen.',
  ok_register_password: 'Uw account is geregistreerd. U kunt nu inloggen.',
  ok_register_totp_confirm: 'Uw authenticator is geregistreerd.',
  ok_register_totp_request: 'De geheime sleutel voor uw authenticator is: $(secret)s. Voer hieronder de code van uw authenticator in:',
  ok_reset_confirm: 'Uw wachtwoord is gewijzigd. U kunt nu inloggen.',
  ok_reset_request: 'Een bericht met een link om uw wachtwoord te wijzigen is verstuurd.',
  ok_update_user: 'Uw account is gewijzigd.',
  option_theme_dark: 'Donker',
  option_theme_light: 'Licht',
  sms_text_login_hotp: 'Uw eenmalige code is: $(token)s',
  sms_text_register: 'Er is een account geregisteerd. Als u dit niet zelf hebt gedaan, dan kunt u dit ongedaan maken via [deze link]($(url)s).',
  sms_text_register_hotp: 'Uw eenmalige code is: $(token)s',
  sms_text_register_identity: 'Er is een account geregistreerd. U kunt deze registratie bevestigen via [deze link]($(url)s).',
  sms_text_unregister_hotp: 'Uw eenmalige code is: $(token)s',
  sms_text_unregister_identity: 'Er is een aanvraag gedaan om uw account te verwijderen. U kunt uw account verwijderen via [deze link]($(url)s).',
  title_login: 'Inloggen',
  title_register: 'Registeren',
  title_reset_confirm: 'Wachtwoord wijzigen',
  title_reset_request: 'Wachtwoord vergeten',
  title_user: 'Account',
  title_user_auth: 'Beveiliging',
  title_user_auth_password: 'Wachtwoord',
  title_user_auth_password_required: 'Wachtwoord (verplicht)',
  title_user_email: 'Berichten',
  title_user_i18n: 'Taal & tijdzone',
  title_user_i18n_locale: 'Taal',
  title_user_i18n_time_zone: 'Tijdzone',
  title_user_identity: 'Identiteit',
  title_user_identity_email: 'E-mail',
  title_user_identity_etu: 'E-mail, telefoon of gebruikersnaam',
  title_user_identity_name: 'Naam',
  title_user_identity_tel: 'Telefoon',
  title_user_identity_username: 'Gebruikersnaam',
  tooltip_locale: 'Wijzig de taal',
  tooltip_theme: 'Wijzig het thema'
}
