export const nl = {
  button_cancel: 'Annuleren',
  button_ok: 'OK',
  err_form_bad_input_color: 'Voer een geldige kleur in',
  err_form_bad_input_date: 'Voer een geldige datum in',
  err_form_bad_input_email: 'Voer een geldig e-mailadres in',
  err_form_bad_input_number: 'Voer een geldig getal in',
  err_form_bad_input_range: 'Voer een geldig getal in',
  err_form_bad_input_tel: 'Voer een geldig telefoonnummer in',
  err_form_bad_input_time: 'Voer een geldige tijd in',
  err_form_bad_input_url: 'Voer een geldige URL in',
  err_form_pattern_mismatch: 'Voer een geldige waarde in als :pattern',
  err_form_range_overflow: 'Voer een getal in kleiner dan :max',
  err_form_range_underflow: 'Voer een getal in groter dan :min',
  err_form_step_mismatch: 'Voer een getal in als veelvoud van :min',
  err_form_too_long: 'Voer een tekst in korter dan :max tekens',
  err_form_too_short: 'Voer een tekst in langer dan :min tekens',
  err_form_type_mismatch_color: 'Voer een geldige kleur in',
  err_form_type_mismatch_date: 'Voer een geldige datum in',
  err_form_type_mismatch_email: 'Voer een geldig e-mailadres in',
  err_form_type_mismatch_number: 'Voer een geldig getal in',
  err_form_type_mismatch_range: 'Voer een geldig getal in',
  err_form_type_mismatch_tel: 'Voer een geldig telefoonnummer in',
  err_form_type_mismatch_time: 'Voer een geldige tijd in',
  err_form_type_mismatch_url: 'Voer een geldige URL in',
  err_form_value_missing: 'Dit veld is verplicht',
  err_idb: 'Onbekende fout (:message)',
  err_recorder: 'Onbekende fout (:message)',
  err_requester: 'Onbekende fout (:message)',
  err_requester_400: 'De invoer is ongeldig.',
  err_requester_401: 'U hebt geen toegang tot deze gegevens.',
  err_requester_403: 'U hebt geen toegang tot deze gegevens.',
  err_requester_404: 'De gegevens konden niet worden gevonden.',
  err_requester_405: 'De aanvraag is ongeldig.',
  err_requester_415: 'De aanvraag is ongeldig.',
  err_requester_500: 'Er is een serverfout opgetreden.',
  err_requester_502: 'Er is een serverfout opgetreden.',
  err_svg: 'Onbekende fout (:message)',
  err_worker: 'Onbekende fout (:message)'
}
