export const nl = {
  button_cancel: 'Annuleren',
  button_ok: 'OK',
  err_idb: 'Onbekende fout (:message)',
  err_recorder: 'Onbekende fout (:message)',
  err_requester: 'Onbekende fout (:message)',
  err_requester_400: 'De invoer is ongeldig.',
  err_requester_401: 'U hebt geen toegang tot deze gegevens.',
  err_requester_403: 'U hebt geen toegang tot deze gegevens.',
  err_requester_404: 'De gegevens konden niet worden gevonden.',
  err_requester_405: 'De aanvraag is ongeldig.',
  err_requester_415: 'De aanvraag is ongeldig.',
  err_requester_500: 'Er is een serverfout opgetreden.',
  err_requester_502: 'Er is een serverfout opgetreden.',
  err_svg: 'Onbekende fout (:message)',
  err_validator_bad_input_checkbox: 'Voer een geldige waarde in',
  err_validator_bad_input_color: 'Voer een geldige kleur in',
  err_validator_bad_input_date: 'Voer een geldige datum in',
  err_validator_bad_input_email: 'Voer een geldig e-mailadres in',
  err_validator_bad_input_number: 'Voer een geldig getal in',
  err_validator_bad_input_radio: 'Voer een geldige waarde in',
  err_validator_bad_input_range: 'Voer een geldig getal in',
  err_validator_bad_input_select: 'Voer een geldige waarde in',
  err_validator_bad_input_text: 'Voer een geldige tekst in',
  err_validator_bad_input_time: 'Voer een geldige tijd in',
  err_validator_bad_input_url: 'Voer een geldige URL in',
  err_validator_pattern_mismatch: 'Voer een geldige waarde in',
  err_validator_range_overflow: 'Voer een getal in kleiner dan :max',
  err_validator_range_underflow: 'Voer een getal in groter dan :min',
  err_validator_step_mismatch: 'Voer een getal in als veelvoud van :min',
  err_validator_too_long: 'Voer een tekst in korter dan :maxLenght tekens',
  err_validator_too_short: 'Voer een tekst in langer dan :minLength tekens',
  err_validator_type_mismatch_email: 'Voer een geldig e-mailadres in',
  err_validator_type_mismatch_url: 'Voer een geldige URL in',
  err_validator_value_missing: 'Dit veld is verplicht',
  err_worker: 'Onbekende fout (:message)'
}
