version: "3.7"
services:
  postgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: scola
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "0.0.0.0:5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - $PWD/.deploy/postgres/initdb.d:/docker-entrypoint-initdb.d
