./dist/cli/index.js html-sql "src/client/snippets/auth/entities/*.html" ".docker/mssql/docker-entrypoint-initdb.d/lib/00_auth.sql" -d mssql -D scola
./dist/cli/index.js html-sql "src/client/snippets/auth/entities/*.html" ".docker/mysql/docker-entrypoint-initdb.d/lib/00_auth.sql" -d mysql -D scola
./dist/cli/index.js html-sql "src/client/snippets/auth/entities/*.html" ".docker/pgsql/docker-entrypoint-initdb.d/lib/00_auth.sql" -d pgsql -D scola
./dist/cli/index.js html-sql "src/client/snippets/queue/entities/*.html" ".docker/mssql/docker-entrypoint-initdb.d/lib/01_queue.sql" -d mssql -D scola
./dist/cli/index.js html-sql "src/client/snippets/queue/entities/*.html" ".docker/mysql/docker-entrypoint-initdb.d/lib/01_queue.sql" -d mysql -D scola
./dist/cli/index.js html-sql "src/client/snippets/queue/entities/*.html" ".docker/pgsql/docker-entrypoint-initdb.d/lib/01_queue.sql" -d pgsql -D scola
./dist/cli/index.js html-sql "src/client/snippets/view/entities/*.html" ".docker/mssql/docker-entrypoint-initdb.d/lib/02_view.sql" -d mssql -D scola
./dist/cli/index.js html-sql "src/client/snippets/view/entities/*.html" ".docker/mysql/docker-entrypoint-initdb.d/lib/02_view.sql" -d mysql -D scola
./dist/cli/index.js html-sql "src/client/snippets/view/entities/*.html" ".docker/pgsql/docker-entrypoint-initdb.d/lib/02_view.sql" -d pgsql -D scola
