name: Deploy Continuously
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Continuously
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 13
      
      - name: Install dependencies
        run: yarn install

      - name: Lint source code
        run: yarn lint

      - name: Test source code
        run: yarn test
      
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
