name: Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test

      - name: Make
        run: yarn run make

      - name: Release
        run: yarn semantic-release
