name: Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Start containers
        run: docker-compose --file .docker/compose.yaml --file .docker/mssql/compose.yaml --file .docker/mysql/compose.yaml --file .docker/postgres/compose.yaml --file .docker/redis/compose.yaml up --detach

      - name: Test
        run: |
          sleep 30 
          npm run test

      - name: Stop containers
        run: docker-compose --file .docker/compose.yaml --file .docker/mssql/compose.yaml --file .docker/mysql/compose.yaml --file .docker/postgres/compose.yaml --file .docker/redis/compose.yaml down

      - name: Make
        run: npm run make

      - name: Release
        run: npm run semantic-release
